/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-5ZWI3s0u4FA5n1nlbO27CXakarOS2IPZIZOyXYiJtjSxR0xeuXVO6abfnTP8r8ORbrd-2B4RJxIRR0OcvlgzEJ4sM5O4PnjKhr46mzRQ7ijtk3meOoAORWKt",
  "tt": "tt-1-dn-kX6NJecSyeRczkiS-mbH4m2O-XFsM64uG4rs-jRY=",
  "version": "2020-11-20"
}

export default ebconfig;